pages:
  - amazon-bedrock
  - analytics
  - changelog
  - checkpointing
  - chrome
  - claude-code-on-the-web
  - cli-reference
  - common-workflows
  - costs
  - data-usage
  - desktop
  - devcontainer
  - discover-plugins
  - github-actions
  - gitlab-ci-cd
  - google-vertex-ai
  - headless
  - hooks
  - hooks-guide
  - iam
  - interactive-mode
  - jetbrains
  - legal-and-compliance
  - llm-gateway
  - mcp
  - memory
  - microsoft-foundry
  - model-config
  - monitoring-usage
  - network-config
  - output-styles
  - overview
  - plugin-marketplaces
  - plugins
  - plugins-reference
  - quickstart
  - sandboxing
  - security
  - settings
  - setup
  - skills
  - slack
  - slash-commands
  - statusline
  - sub-agents
  - terminal-config
  - third-party-integrations
  - troubleshooting
  - vs-code
